# Generated by Django 2.2.28 on 2024-03-11 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueName', models.CharField(max_length=128, unique=True)),
                ('Location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StageName', models.CharField(max_length=128, unique=True)),
                ('Genre', models.CharField(max_length=128)),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='./media/profile_images')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GigID', models.CharField(max_length=128, unique=True)),
                ('GigName', models.CharField(default='Default Name', max_length=128, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('GigPicture', models.ImageField(blank=True, upload_to='./media/gig_images')),
                ('PerformersStageNames', models.ManyToManyField(to='gigluvver_app.Performer')),
                ('Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigluvver_app.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='./media/profile_images')),
                ('Gigs', models.ManyToManyField(to='gigluvver_app.Gig')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
