# Generated by Django 2.2.28 on 2024-03-19 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GigName', models.CharField(default='Default Name', max_length=128, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('GigPicture', models.ImageField(blank=True, upload_to='gig_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueName', models.CharField(max_length=128, unique=True)),
                ('Location', models.CharField(max_length=128)),
                ('Position', models.CharField(default='55.8724286,-4.2925758', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsPerformer', models.BooleanField(default=False)),
                ('StageName', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('Genre', models.CharField(blank=True, max_length=128)),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='profile_images/')),
                ('UserField', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerformerGig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gigluvver_app.Gig')),
                ('Performers', models.ManyToManyField(blank=True, limit_choices_to={'IsPerformer': True}, to='gigluvver_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='Venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigluvver_app.Venue'),
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gigluvver_app.UserProfile')),
                ('Gigs', models.ManyToManyField(blank=True, to='gigluvver_app.Gig')),
            ],
        ),
    ]
