# Generated by Django 2.1.5 on 2024-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigluvver_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isArtist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stageName',
            field=models.CharField(default='Nameless Artist', max_length=30),
        ),
        migrations.DeleteModel(
            name='ArtistProfile',
        ),
    ]
