# Generated by Django 2.2.28 on 2024-03-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigluvver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='GigName',
            field=models.CharField(default='Default Name', max_length=128),
        ),
        migrations.AlterField(
            model_name='gig',
            name='ProfilePicture',
            field=models.ImageField(blank=True, upload_to='./media/gig_images'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='ProfilePicture',
            field=models.ImageField(blank=True, upload_to='./media/profile_images'),
        ),
    ]
