# Generated by Django 2.2.28 on 2024-03-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigluvver_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='UserField',
        ),
    ]
