# Generated by Django 2.2.28 on 2024-03-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigluvver_app', '0002_auto_20240310_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='ProfilePicture',
            new_name='GigPicture',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='PerformerStageNames',
            new_name='PerformersStageNames',
        ),
    ]
