# Generated by Django 2.1.5 on 2024-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigluvver_app', '0002_auto_20240307_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isArtist',
            new_name='is_artist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stageName',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stage_name',
            field=models.CharField(default='Artist Name', max_length=30),
        ),
    ]
